### ISSUE TITLE
Fehlende Amtszeit für TOPF-Hauptverantwortliche

### ISSUE THREAD

**Issue by behrmann** [ZaPF/Satzung_der_ZaPF#18]
Bei den Hauptverantwortlichen des TOPFes steht zwar, wann die Amtszeiten beginnen. Ein Ende ist aber nicht definiert.

**Comment by fabianfreyer** [comment]
Also bin ich technisch gesehen noch im Amt?

**Comment by behrmann** [comment]
Jop, und ich auch. :)
