### ISSUE TITLE
änderung der satzung einführung eines pool gremiums

### ISSUE THREAD

**Issue by SchwertPhisch** [ZaPF/Satzung_der_ZaPF#30]
es ist manschen leuten aufgefallen das es probleme mit akreditierungs sachen gibt deshalb soll das problem angepackt werden

**Comment by SchwertPhisch** [comment]
würde vorschlagen wird eine haupt person gewählt die sich dadrum kümmert neben und mit dem Stapf falls mal im stapf keiner ne ahnung halt 
zusätlich müssen alle akk pool wiki einträge die dafür wichtig sind da rein

**Comment by niklasjam** [comment]
Was wäre der Aufgabenbereich eines solchen Gremiums? Mir fällt akut die Durchführung des Akkreditierungsworkshops und die Abfrage und Weitergabe von gewählten Menschen an den Pool ein. Und ggf. ASIIN.

**Comment by n4TRUAL** [comment]
Aufgrund von inaktivität erstmal geschlossen.
